DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS boleto;

CREATE TABLE service (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE boleto (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_id INTEGER NOT NULL REFERENCES service(id),
    filename TEXT NOT NULL,
    amount INTEGER NOT NULL,
    issue_ts INTEGER NOT NULL,
    expiry_ts INTEGER NOT NULL,
    payment_ts INTEGER
);
