DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS boleto;

CREATE TABLE service (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE boleto (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_id INTEGER NOT NULL REFERENCES service(id),
    filename VARCHAR NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL
)
