DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS payment;

CREATE TABLE service (
    service_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE payment (
    payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_id INTEGER NOT NULL REFERENCES service(service_id),
    filename VARCHAR NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL
)
